---
# tasks file for demo
- name: Create a db service
  k8s:
    state: present
    definition: "{{ lookup('file', '/opt/ansible/roles/demo/files/db-svc.yaml') }}"
- name: Create a db deployment
  k8s:
    state: present
    definition: "{{ lookup('file', '/opt/ansible/roles/demo/files/db-deployment.yaml') }}"

- name: Create a api service
  k8s:
    state: present
    definition: "{{ lookup('file', '/opt/ansible/roles/demo/files/api-svc.yaml') }}"
- name: Create a api deployment
  k8s:
    state: present
    definition: "{{ lookup('file', '/opt/ansible/roles/demo/files/api-deployment.yaml') }}"

- name: Create a web service
  k8s:
    state: present
    definition: "{{ lookup('file', '/opt/ansible/roles/demo/files/web-svc.yaml') }}"
- name: Create a web deployment
  k8s:
    state: present
    definition: "{{ lookup('file', '/opt/ansible/roles/demo/files/web-deployment.yaml') }}"
